import assert from "node:assert/strict";
import { test } from "node:test";
import { address, getBase58Encoder, type Address } from "@solana/kit";
import fixture from "./fixtures/holding-chain.json" with { type: "json" };
import type { Instance } from "../lib/endowment.ts";
import { holdPda } from "../lib/holding/client.ts";
import { loadHolding } from "../lib/holding/wallet.ts";
import { concat, decodeAccount, encode, schema } from "../lib/holding/codec.ts";
import type { Consent, Receipt } from "../lib/holding/types.ts";

const inst: Instance = {
  program: address(fixture.program), config: address(fixture.config),
  coinMint: address(fixture.coinMint), dividendMint: address(fixture.dividendMint),
  coinTokenProgram: address(fixture.coinTokenProgram), dividendTokenProgram: address(fixture.dividendTokenProgram),
};
type Info = { owner: string; data: [string, string] };
type Row = { pubkey: Address; account: Info };
type Query = {
  encoding: string; commitment: string; withContext: boolean; minContextSlot: bigint;
  filters: { memcmp: { offset: bigint; bytes: string; encoding: string } }[];
};
const records = fixture.records as unknown as Record<string, Info>;
const owner = address(fixture.owner);
const receiptKey = await holdPda(inst, "receipt", owner, 0n);
const consentKey = await holdPda(inst, "consent", owner);
const receiptTemplate = decodeAccount<Receipt>("PendingCollection", Buffer.from(records[receiptKey].data[0], "base64"));
const consentTemplate = decodeAccount<Consent>("CollectionConsent", Buffer.from(records[consentKey].data[0], "base64"));
function encoded(name: string, value: unknown): Info {
  return {
    owner: inst.program,
    data: [Buffer.from(concat(Uint8Array.from(schema.accounts[name]), encode({ defined: { name } }, value))).toString("base64"), "base64"],
  };
}
/** A read-only RPC over Rust-generated bytes that applies the actual RPC filters. */
function bank(hide: string[] = [], overrides: Record<string, Info> = {}) {
  const accounts = { ...records, ...overrides };
  const calls: Address[][] = [];
  const queries: { program: Address; config: Query }[] = [];
  const rpc = {
    getMultipleAccounts: (addresses: Address[]) => ({
      send: async () => {
        calls.push(addresses);
        return { context: { slot: 100n }, value: addresses.map((a) => (hide.includes(a) ? null : (accounts[a] ?? null))) };
      },
    }),
    getProgramAccounts: (program: Address, config: Query) => ({
      send: async () => {
        queries.push({ program, config });
        const rows = Object.entries(accounts).filter(([key, info]) => {
          const bytes = Buffer.from(info.data[0], "base64");
          return !hide.includes(key) && info.owner === program && config.filters.every(({ memcmp }) => {
            const expected = getBase58Encoder().encode(memcmp.bytes);
            return expected.every((byte, i) => bytes[Number(memcmp.offset) + i] === byte);
          });
        }).reverse().map(([pubkey, account]) => ({ pubkey: address(pubkey), account }));
        return { context: { slot: 101n }, value: rows };
      },
    }),
  };
  return { rpc, calls, queries };
}
function rpcWithRows(rows: Row[]) {
  return {
    ...bank().rpc,
    getProgramAccounts: () => ({ send: async () => ({ context: { slot: 101n }, value: rows }) }),
  };
}

test("a wallet sees its switch and all held collections in two filtered reads", async () => {
  const { rpc, calls, queries } = bank();
  const holding = await loadHolding(rpc, inst, owner);
  assert.equal(holding.ready, true);
  assert.equal(holding.consent?.enabled, true);
  assert.equal(holding.consent?.next_nonce, 1n);
  assert.equal(holding.receipts.length, 1);
  assert.equal(holding.receipts[0].amount, 1000n);
  assert.equal(holding.receipts[0].owner, owner);
  assert.equal(calls.length, 1);
  assert.equal(queries.length, 1);
  assert.equal(queries[0].program, inst.program);
  assert.equal(queries[0].config.minContextSlot, 100n);
  assert.equal(queries[0].config.withContext, true);
  assert.deepEqual(queries[0].config.filters.map(({ memcmp }) => [memcmp.offset, memcmp.encoding]), [[0n, "base58"], [8n, "base58"], [40n, "base58"]]);
});

test("a settled collection is gone, and a wallet that never joined has nothing", async () => {
  const settled = await loadHolding(bank([receiptKey]).rpc, inst, owner);
  assert.deepEqual(settled.receipts, []);
  assert.equal(settled.consent?.enabled, true);

  const stranger = address(fixture.reviewer);
  const { rpc, queries } = bank();
  assert.deepEqual(await loadHolding(rpc, inst, stranger), { ready: true, consent: null, receipts: [] });
  assert.equal(queries.length, 1);
});

test("before collection is set up, joining is not offered", async () => {
  const policy = await holdPda(inst, "policy");
  assert.equal((await loadHolding(bank([policy]).rpc, inst, owner)).ready, false);
});

test("more than forty pending receipts are all returned, oldest first", async () => {
  const extra: Record<string, Info> = {
    [consentKey]: encoded("CollectionConsent", { ...consentTemplate, next_nonce: 65n }),
  };
  for (let nonce = 1n; nonce < 65n; nonce++) {
    extra[await holdPda(inst, "receipt", owner, nonce)] = encoded("PendingCollection", {
      ...receiptTemplate, nonce, collected_at: receiptTemplate.collected_at + nonce / 2n,
    });
  }
  const { rpc, calls, queries } = bank([], extra);
  const holding = await loadHolding(rpc, inst, owner);
  assert.deepEqual(holding.receipts.map((r) => r.nonce), Array.from({ length: 65 }, (_, i) => BigInt(i)));
  assert.equal(holding.receipts.reduce((sum, r) => sum + r.amount, 0n), 65_000n);
  assert.equal(calls.length, 1);
  assert.equal(queries.length, 1);
});

test("old receipts survive high nonces and gaps from settled or no-op collections", async () => {
  const sparseNonce = 1_000_050n;
  const { rpc, queries } = bank([], {
    [consentKey]: encoded("CollectionConsent", { ...consentTemplate, next_nonce: 2_000_000n }),
    [await holdPda(inst, "receipt", owner, sparseNonce)]: encoded("PendingCollection", {
      ...receiptTemplate, nonce: sparseNonce, collected_at: receiptTemplate.collected_at + 100n,
    }),
  });
  assert.deepEqual((await loadHolding(rpc, inst, owner)).receipts.map((r) => r.nonce), [0n, sparseNonce]);
  assert.equal(queries.length, 1);
});

test("receipt recovery does not depend on consent existence, nonce, or enabled state", async () => {
  for (const rpc of [
    bank([consentKey]).rpc,
    bank([], { [consentKey]: encoded("CollectionConsent", { ...consentTemplate, next_nonce: 0n, enabled: false }) }).rpc,
  ]) assert.equal((await loadHolding(rpc, inst, owner)).receipts.length, 1);
});

test("other owners and configurations are excluded by the RPC filters", async () => {
  const stranger = address(fixture.reviewer);
  const otherInst = { ...inst, config: address(fixture.collector) };
  const { rpc } = bank([], {
    [await holdPda(inst, "receipt", stranger, 0n)]: encoded("PendingCollection", { ...receiptTemplate, owner: stranger }),
    [await holdPda(otherInst, "receipt", owner, 0n)]: encoded("PendingCollection", { ...receiptTemplate, config: otherInst.config }),
  });
  assert.deepEqual((await loadHolding(rpc, inst, owner)).receipts, [receiptTemplate]);
});

test("invalid identities, program owners, PDAs, encodings and layouts fail the complete read", async () => {
  const variants: Row[] = [
    { pubkey: receiptKey, account: encoded("PendingCollection", { ...receiptTemplate, owner: address(fixture.reviewer) }) },
    { pubkey: receiptKey, account: encoded("PendingCollection", { ...receiptTemplate, config: address(fixture.collector) }) },
    { pubkey: address(fixture.collector), account: records[receiptKey] },
    { pubkey: receiptKey, account: { ...records[receiptKey], owner: fixture.dividendTokenProgram } },
    { pubkey: receiptKey, account: { ...records[receiptKey], data: [records[receiptKey].data[0], "base58"] } },
    { pubkey: receiptKey, account: { ...records[receiptKey], data: [Buffer.from([1, 2, 3]).toString("base64"), "base64"] } },
  ];
  for (const row of variants) await assert.rejects(loadHolding(rpcWithRows([row]), inst, owner));
  const good = { pubkey: receiptKey, account: records[receiptKey] };
  await assert.rejects(loadHolding(rpcWithRows([good, good]), inst, owner), /duplicate/);
  await assert.rejects(loadHolding(rpcWithRows([good, variants[1]]), inst, owner), /Invalid/);
});

test("failed, malformed, incomplete or stale RPC responses never become zero held funds", async () => {
  const readFailure = { send: async () => { throw new Error("RPC unavailable"); } };
  await assert.rejects(loadHolding({ ...bank().rpc, getProgramAccounts: () => readFailure }, inst, owner), /RPC unavailable/);
  for (const response of [
    { context: { slot: 101n } },
    { value: [] },
    { context: { slot: 99n }, value: [] },
    { context: { slot: 101n }, value: {} },
    { context: { slot: 101n }, value: [null] },
  ]) await assert.rejects(loadHolding({ ...bank().rpc, getProgramAccounts: () => ({ send: async () => response }) }, inst, owner));
  await assert.rejects(loadHolding({
    ...bank().rpc,
    getMultipleAccounts: () => ({ send: async () => ({ context: { slot: 100n }, value: [null] }) }),
  }, inst, owner), /Incomplete/);
});

test("invalid policy or consent account data is an error, not a missing enrollment", async () => {
  await assert.rejects(loadHolding(bank([], {
    [consentKey]: { ...records[consentKey], owner: fixture.dividendTokenProgram },
  }).rpc, inst, owner), /owner/);
  await assert.rejects(loadHolding(bank([], {
    [consentKey]: encoded("CollectionConsent", { ...consentTemplate, owner: address(fixture.reviewer) }),
  }).rpc, inst, owner), /identity/);
});

test("joining, rejoining and taking a collection back each fit one transaction", async () => {
  const kit = await import("@solana/kit");
  const token = await import("@solana-program/token-2022");
  const { getSetComputeUnitLimitInstruction, getSetComputeUnitPriceInstruction } = await import("@solana-program/compute-budget");
  const { registerLandlordIx, resyncBaselineIx, authorityPda, ata } = await import("../lib/endowment.ts");
  const { consentIx, settleIx } = await import("../lib/holding/client.ts");
  const signer = kit.createNoopSigner(owner);
  const dividendAccount = await ata(owner, inst.dividendMint, inst.dividendTokenProgram);
  const coinAccount = await ata(owner, inst.coinMint, inst.coinTokenProgram);
  const tokenProgram = inst.dividendTokenProgram as typeof token.TOKEN_2022_PROGRAM_ADDRESS;
  // What the Delegate button sends, in order (components/DelegatePanel.tsx).
  const before = [
    token.getCreateAssociatedTokenIdempotentInstruction({ payer: signer, owner, mint: inst.dividendMint, ata: dividendAccount, tokenProgram }),
    token.getCreateAssociatedTokenIdempotentInstruction({ payer: signer, owner, mint: inst.coinMint, ata: coinAccount, tokenProgram }),
    token.getApproveCheckedInstruction(
      { source: dividendAccount, mint: inst.dividendMint, delegate: await authorityPda(inst.program, inst.config), owner: signer, amount: 18446744073709551615n, decimals: 6 },
      { programAddress: tokenProgram },
    ),
  ];
  const enable = await consentIx(inst, signer, "enable_collection");
  const held = (await loadHolding(bank().rpc, inst, owner)).receipts[0];
  const flows = {
    join: [...before, await registerLandlordIx(inst, signer, dividendAccount, coinAccount), enable],
    rejoin: [...before, await resyncBaselineIx(inst, signer, dividendAccount), enable],
    takeBack: [await settleIx(inst, held, signer, false)],
  };
  for (const [name, ixs] of Object.entries(flows)) {
    // Wallets add their own compute-budget instructions; leave room for both.
    const message = kit.appendTransactionMessageInstructions(
      [getSetComputeUnitLimitInstruction({ units: 400_000 }), getSetComputeUnitPriceInstruction({ microLamports: 100_000n }), ...ixs],
      kit.setTransactionMessageLifetimeUsingBlockhash(
        { blockhash: kit.blockhash("11111111111111111111111111111111"), lastValidBlockHeight: 1n },
        kit.setTransactionMessageFeePayer(owner, kit.createTransactionMessage({ version: 0 })),
      ),
    );
    const size = kit.getTransactionEncoder().encode(kit.compileTransaction(message)).length;
    assert.ok(size <= 1232, `${name} uses ${size} bytes`);
  }
});
